all:
	gcc challenge2.c -o challenge2
	gcc challenge5.c -o challenge5
	gcc challenge6.c -o challenge6
	gcc challenge8.c -o challenge8
	gcc challenge10.c -o challenge10
	gcc challenge11.c -o challenge11
	gcc challenge12.c -o challenge12
	gcc challenge13.c -o challenge13
	gcc challenge14.c -o challenge14
